### ISSUE TITLE
功能请求 - 大佬可以安排个b站多账号版本吗？

### ISSUE THREAD

**Issue by Yakumo-Yukari** [XcantloadX/AutoCloudSign#10]
比如像我这样有2个B站账号 就只能挂一个上去 另一个就没办法了

**Comment by XcantloadX** [comment]
见 [Wiki](https://github.com/XcantloadX/AutoCloudSign/wiki/%E5%AE%89%E8%A3%85#%E5%A1%AB%E5%86%99-cookie)

**Comment by Yakumo-Yukari** [comment]
> 见 [Wiki](https://github.com/XcantloadX/AutoCloudSign/wiki/%E5%AE%89%E8%A3%85#%E5%A1%AB%E5%86%99-cookie)

大佬  执行命令 我是直接用的 `php start.php`


  我没用
`cd ~/cloudsign/
#启动 PHP 内置服务器
php -S 0.0.0.0:8080
#每天早上六点定时访问 http://0.0.0.0:8080/start.php
echo "0 0 6 * * ? * curl http://0.0.0.0:8080/start.php" | crontab
service cron start`
 没有影响吧？

**Comment by XcantloadX** [comment]
我刚刚试了试
好像也行

**Comment by Yakumo-Yukari** [comment]
> 我刚刚试了试
> 好像也行

哦 那就好
