### ISSUE TITLE
大佬 json多账号的要怎么配置呢 这样可以吗？

### ISSUE THREAD

**Issue by Yakumo-Yukari** [XcantloadX/AutoCloudSign#13]
{"JOWDS":{"script":"TieBa",
        "name": "示例账号1",
        "cookie": "这里填 Cookie........",
        "note": "只是个示例......",
        "data": null
    },
    "JOWDS2":{"script":"TieBa",
        "name": "示例账号2",
        "cookie": "这里填 Cookie........",
        "note": "只是个示例......",
        "data": null
    }
}

多账户需要这样配置吗

**Comment by XcantloadX** [comment]
如果你用 master 分支，在 conf.php 里改，用 ui 分支，访问 /web/index.php，在网页里改
