### ISSUE TITLE
Bug 反馈 - [B站cookie中间一段带有b_timer={"ffp":{"333.1007.fp.risk_3EFBB869":"181C12EB940","333.42.fp.risk_3AFCA869":"181C12EBB05"}};]

### ISSUE THREAD

**Issue by Yakumo-Yukari** [XcantloadX/AutoCloudSign#15]
* 问题脚本：B站和BigFun
* 问题描述：不知道是否是B站更新了 以前是没有[b_timer={"ffp":{"333.1007.fp.risk_3EFBB869":"181C12EB940","333.42.fp.risk_3EFBB869":"181C12EBB05"}};]的  现在的cookie就有了  执行后就会报错
* 报错信息：<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

PHP Parse error:  syntax error, unexpected 'ffp' (T_STRING), expecting ')' in /www/wwwroot/AutoCloudSign/conf.php on line 38

Parse error: syntax error, unexpected 'ffp' (T_STRING), expecting ')' in /www/wwwroot/AutoCloudSign/conf.php on line 38

**Comment by Yakumo-Yukari** [comment]
B站主站可以通过 去掉b_timer后不报错  但是  bigfun去掉 b_timer后就会报  <br/>[2022-07-03 07:41:54][BigFun][Error] Cookie 已失效！

**Comment by XcantloadX** [comment]
用[这个工具](http://www.lzltool.com/Escape/StringEscape)把 Cookie 转义之后再试

**Comment by Yakumo-Yukari** [comment]
> 

还是不行  不知道是不是bigfun的签到脚本有问题了还是怎么回事，一直提示失效

**Comment by Yakumo-Yukari** [comment]
> 用[这个工具](http://www.lzltool.com/Escape/StringEscape)把 Cookie 转义之后再试

还是不行 不知道是不是bigfun的签到脚本有问题了还是怎么回事，一直提示失效

**Comment by XcantloadX** [comment]
试试修改后的版本

**Comment by Yakumo-Yukari** [comment]
> 试试修改后的版本

好的

**Comment by Yakumo-Yukari** [comment]
> 试试修改后的版本

完美解决了，谢谢大佬
