### ISSUE TITLE
[BUG 反馈] >>>腾讯云函数部署依然报错 <<<

### ISSUE THREAD

**Issue by Yakumo-Yukari** [XcantloadX/AutoCloudSign#17]
## 问题描述
> 使用云函数部署后点击测试报错
### 复现步骤
> 直接部署测试

### 运行环境
> 越详细越好

> 1.Win、Linux、PHP 主机、云函数或其他？

云函数

> 2.从命令行直接运行的还是通过 Web 服务器触发的？

部署测试

> 3.PHP 版本

PHP7.4

## 错误日志
```
日志:

暂无 UIException: function main_handler not found in /var/runtime/php74/bootstrap.php:44

START RequestId: c93f5fc2-77eb-4db9-8649-f13c1c7f8c7e

Stack trace:

#0 /var/runtime/php74/bootstrap.php(204): __scf_bootstrap_\EventHandler->handle(Object(stdClass), Object(stdClass))

#1 /var/runtime/php74/bootstrap.php(227): __scf_bootstrap_\__main_for_scf()

#2 {main}

ERROR RequestId: c93f5fc2-77eb-4db9-8649-f13c1c7f8c7e Result: Exception: function main_handler not found in /var/runtime/php74/bootstrap.php:44 Stack trace: #0 /var/runtime/php74/bootstrap.php(204): __scf_bootstrap_\EventHandler->handle(Object(stdClass), Object(stdClass)) #1 /var/runtime/php74/bootstrap.php(227): __scf_bootstrap_\__main_for_scf() #2 {main}

END RequestId: c93f5fc2-77eb-4db9-8649-f13c1c7f8c7e

Report RequestId: c93f5fc2-77eb-4db9-8649-f13c1c7f8c7e Duration: 1ms Memory: 256MB MemUsage: 6.63MB

```

账号配置

![捕获1](https://user-images.githubusercontent.com/12076232/183195194-4e7c5db0-c291-4f2f-9d63-e5c8857cabbd.PNG)

**Comment by XcantloadX** [comment]
执行方法应该是`index_tencent.main_handler`  
另外你再试试 Ubuntu 上运行

**Comment by Yakumo-Yukari** [comment]
> 执行方法应该是`index_tencent.main_handler` 另外你再试试 Ubuntu 上运行

云函数 和 ubuntu环境 都可以正常签到了

但是签到后有个警告

PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /www/AutoCloudSign/script/tieba.php on line 90
[2022-08-07 01:01:41][Default][Info] 已完成所有签到任务
[2022-08-07 01:01:41][Default][Info] 完成


PHP是7.4  

签到代码是拉的最新的

**Comment by Yakumo-Yukari** [comment]
大佬请教一下  云函数 自动触发的时候 怎么判断是否成功签到呢   测试的时候用命令终端有返回信息  如果是每天触发是如何判断是否成功呢

**Comment by XcantloadX** [comment]
> 大佬请教一下 云函数 自动触发的时候 怎么判断是否成功签到呢 测试的时候用命令终端有返回信息 如果是每天触发是如何判断是否成功呢

你可以用推送功能。不过我很久都没有测试过了，应该没啥问题
