### ISSUE TITLE
签到100个吧之后就开始报2150040

### ISSUE THREAD

**Issue by LazyShiro** [XcantloadX/AutoCloudSign#4]
看样子好像是操作频繁需要验证了，这个大佬是怎么解决的呀，还是说只能签到100个。

报错提示如下
{"no":2150040,"error":"need vcode","data":{"captcha_vcode_str":"captchaservice32373632456d5261...","captcha_code_type":0,"str_reason":"\u62d2\u7edd"}}

**Comment by XcantloadX** [comment]
我研究了一下，发现这个验证码随便输什么字符都能通过。。。

**Comment by XcantloadX** [comment]
试试修改后的版本
