### ISSUE TITLE
老大可以写一个前端的添加吗

### ISSUE THREAD

**Issue by ilhmtfmlt2** [XcantloadX/AutoCloudSign#6]

**Comment by XcantloadX** [comment]
UI 在计划之中，打算之后加
目前的话，还是手动编辑吧。。。
反正只要一次就好



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月17日(周四) 下午5:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [XcantloadX/AutoCloudSign] 老大可以写一个前端的添加吗 (#6)

**Comment by ilhmtfmlt2** [comment]
其实不是老大，主要是不能再前台添加cookie（悲伤ing）

**Comment by XcantloadX** [comment]
这个我也不知道什么时候能加上。。。
学生党时间少。。。

**Comment by ilhmtfmlt2** [comment]
老大加油（手动狗头）

**Comment by ilhmtfmlt2** [comment]
> 这个我也不知道什么时候能。。。加上
> 学生党时间少。。。

加油老大（狗头）

**Comment by ilhmtfmlt2** [comment]
老大，已经二十天没更新了

**Comment by XcantloadX** [comment]
快了快了，还有十来天。。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月9日(周五) 上午9:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XcantloadX/AutoCloudSign] 老大可以写一个前端的添加吗 (#6)




 
老大，已经二十天没更新了

**Comment by XcantloadX** [comment]
已加，在 [ui 分支](https://github.com/XcantloadX/AutoCloudSign/tree/ui) 里，变化比较大
